name:                bifurcation
version:             0.1.0.0
github:              "fabricatedmath/bifurcation"
license:             BSD3
author:              "Charles Durham"
maintainer:          "fabricatedmath@gmail.com"
copyright:           "2018 Charles Durham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fabricatedmath/bifurcation#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate
- two-danode
- lens
- linear
- linear-accelerate
- colour-accelerate
- accelerate-llvm
- accelerate-llvm-ptx
- pipes-graphics-accelerate
- pipes
- pipes-safe

library:
  source-dirs: src

executables:
  bifurcation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bifurcation

tests:
  bifurcation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bifurcation
